---
# tasks file for role_apt

- name: Fix-broken installs in-case something need to be fixed before update upgrade
  become: true
  ansible.builtin.shell:
    cmd: set -o pipefail && echo "Y" | sudo apt --fix-broken install
  changed_when: false
  failed_when: false
  retries: 1
  delay: 5
  register: result
  until: result is success

- name: Apt-get update and upgrade
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Make sure apt packages are present
  become: true
  ansible.builtin.apt:
    name: "{{ default_apt_packages + additional_apt_packages }}"
    state: present
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: Make sure python3.x ppa is present
  become: true
  ansible.builtin.apt_repository:
    filename: "deadsnakes-ubuntu-ppa-jammy"
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/deadsnakes-ubuntu-ppa.gpg] http://ppa.launchpad.net/deadsnakes/ppa/ubuntu jammy main"
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is success

- name: Make sure python3.9, python3.9-distutils, and other python3.9 packages are present
  become: true
  ansible.builtin.apt:
    name:
      - python3.9
      - python3.9-dev
      - python3.9-distutils
      - python3.9-venv
      - python3.9-tk
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is success

- name: Make sure python3.8 and python3.8-distutils are present
  become: true
  ansible.builtin.apt:
    name:
      - python3.8
      - python3.8-distutils
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is success

- name: Make sure FFmpeg 5.x ppa:savoury1/ffmpeg4 is present
  throttle: 2
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:savoury1/ffmpeg4"
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is success
  when: (ansible_distribution + ansible_distribution_version) != "Ubuntu22.04"

- name: Make sure FFmpeg 5.x ppa:savoury1/ffmpeg5 is present
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:savoury1/ffmpeg5"
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is success
  when: (ansible_distribution + ansible_distribution_version) != "Ubuntu22.04"

- name: Make sure FFmpeg 5.x is present
  throttle: 1
  become: true
  ansible.builtin.apt:
    name:
      - ffmpeg
    state: present
  retries: 3
  delay: 5
  register: result
  until: result is success
