---
# tasks file for role_reboot
- name: Get processes for each current_users
  become: yes
  shell:
      cmd: ps --no-headers -U "{{ item }}" -u "{{ item }}"
  environment:
      PATH: "{{ env_path }}"
  args:
      executable: /bin/zsh
  with_items: "{{ current_users }}"
  register: processes
  changed_when: False
  failed_when: False

- set_fact:
      user_process_dict: "{{ _dict }}"
  vars:
      result: "{{ dict(processes.results | json_query('[?rc == `0`].[item, stdout]')) }}"
      _user: "{{ result.keys() | list | difference(groups['lab_internal_web_host']) }}"
      _processes: "{{ result.values() | map('split', '\n') | list }}"
      _dict: "{{ dict(_user|zip(_processes)) }}"

- debug: msg="{{ user_process_dict }}"

- debug: msg="{{ _user }}"

# - name: Reboot block
#   block:
#     - name: Reboot only machines that no one is running anything
#       become: yes
#       reboot:
#           msg: "Reboot initiated by Ansible"
#           connect_timeout: 5
#           reboot_timeout: 300
#           pre_reboot_delay: 0
#           post_reboot_delay: 60
#           test_command: uptime
#   when: user_process_dict.keys() | length == 0