---
# tasks file for role_reboot
- name: Get processes for each current_users
  become: yes
  shell:
      cmd: ps --no-headers -U "{{ item }}" -u "{{ item }}"
  environment:
      PATH: "{{ env_path }}"
  args:
      executable: /bin/zsh
  with_items: "{{ current_users }}"
  register: processes
  changed_when: False
  failed_when: False

- set_fact:
      _user: "{{ result.keys() | list }}"
      _processes: "{{ result.values() | map('split', '\n') | list }}"
  vars:
      result: "{{ dict(processes.results | json_query('[?rc == `0`].[item, stdout]')) }}"

- set_fact:
      user_process_dict: "{{ dict(_user|zip(_processes)) }}"

- debug: msg="{{ user_process_dict }}"

- name: Reboot block
  block:
    - name: Reboot only machines that no one is running anything
      become: yes
      reboot:
          msg: "Reboot initiated by Ansible"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 60
          test_command: uptime
  when: (user_process_dict.keys() | length == 0) and (inventory_hostname not in groups['lab_internal_web_host'])