---
- name: restart system_reporter
  become: true
  ansible.builtin.systemd:
    name: system_reporter
    state: restarted
    daemon_reload: true

- name: restart system_reporter (user)
  ansible.builtin.systemd:
    name: system_reporter
    state: restarted
    daemon_reload: true
    scope: user

- name: restart redis
  become: true
  ansible.builtin.systemd:
    name: redis-server
    state: restarted

- name: restart internal_web
  become: true
  ansible.builtin.systemd:
    name: internal_web
    state: restarted
    daemon_reload: true
