---
# create new user playbook
- name: Create user on a linux server
  hosts: all
  become: yes
  gather_facts: false
  vars_files:
      - vars/main.yml
      - vars/secrets.yml
  tasks:
      - debug: msg="user:{{ user }} password:{{ password }}"
        delegate_to: localhost
        run_once: True
        
      - name: Reassurance
        pause:
          prompt: "Just making sure you have the correct user and password \
          because this is not easy to be undone. Ctrl+C then A to abort"

      - name: Create a login user
        user:
            name: "{{ user }}"
            password: "{{ password | password_hash('sha512') }}"
            shell: "/bin/bash"
            groups:
                - sudo
                - misl
            state: present

      - name: Add public key to authorized_keys
        authorized_key:
            user: "{{ user }}"
            state: present
            key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
