---
# Deploy updated SvelteKit webapp on the internal web host

- name: Set internal webpage variable
  ansible.builtin.set_fact:
    internal_webpage_dir: "/home/ansible/internal_web"

- name: Create directory for internal web page
  ansible.builtin.file:
    path: "{{ internal_webpage_dir }}"
    owner: ansible
    group: ansible
    mode: "0755"
    state: directory

- name: Copy SvelteKit app files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ internal_webpage_dir }}"
    owner: ansible
    group: ansible
    mode: "0755"
  with_items:
    - "internal-web-page-svelte/src"
    - "internal-web-page-svelte/static"
    - "internal-web-page-svelte/package.json"
    - "internal-web-page-svelte/package-lock.json"
    - "internal-web-page-svelte/svelte.config.js"
    - "internal-web-page-svelte/tsconfig.json"
    - "internal-web-page-svelte/vite.config.ts"
    - "internal-web-page-svelte/.npmrc"

- name: Run npm install
  ansible.builtin.shell:
    cmd: "cd {{ internal_webpage_dir }} && npm install"
  changed_when: true

- name: Run npm build
  ansible.builtin.shell:
    cmd: "cd {{ internal_webpage_dir }} && npm run build"
  changed_when: true

- name: Deploy systemd unit file for internal web
  become: true
  ansible.builtin.template:
    src: internal_web.service.j2
    dest: /etc/systemd/system/internal_web.service
    owner: root
    group: root
    mode: "0644"
  notify: restart internal_web

- name: Enable and start internal web service
  become: true
  ansible.builtin.systemd:
    name: internal_web
    enabled: true
    state: started
    daemon_reload: true
